DROP PROCEDURE "DEMO_PROC";
CREATE PROCEDURE "DEMO_PROC"(
         IN    ID    INTEGER )
LANGUAGE SQLSCRIPT AS
/*********BEGIN PROCEDURE SCRIPT ************/
BEGIN
	DECLARE START_ID INTEGER;
	START_ID := 1;
	WHILE (START_ID <= 737)
	DO
	    update top 1 "SYSTEM"."t_sr" SET "pk_ID" = START_ID WHERE "pk_ID" IS NULL;
	    START_ID = START_ID + 1;
	END WHILE;
END;

call "DEMO_PROC"(1);

ALTER TABLE "t_sr"  ADD PRIMARY KEY ("pk_ID");