set schema SYSTEM;

CREATE FULLTEXT INDEX DESC_IDX ON "t_sr" ("Description") FAST PREPROCESS OFF;

SELECT "Title", LANGUAGE("Description"), SNIPPETS("Description") FROM "t_sr"
WHERE CONTAINS("Description", 'issue OR user', LINGUISTIC);

DROP FULLTEXT INDEX DESC_IDX;

CREATE FULLTEXT INDEX DESC_IDX ON
"t_sr"("Description") FAST PREPROCESS OFF
 LANGUAGE DETECTION ('EN', 'DE', 'FR')
 TEXT ANALYSIS ON;

 
 
 DROP PROCEDURE "DEMO_PROC";
CREATE PROCEDURE "DEMO_PROC"(
         IN    ID    INTEGER )
LANGUAGE SQLSCRIPT AS
/*********BEGIN PROCEDURE SCRIPT ************/
BEGIN
	DECLARE START_ID INTEGER;
	START_ID := 1;
	WHILE (START_ID <= 737)
	DO
	    update top 1 "SYSTEM"."t_sr" SET "pk_ID" = START_ID WHERE "pk_ID" IS NULL;
	    START_ID = START_ID + 1;
	END WHILE;
END;

call "DEMO_PROC"(1);

ALTER TABLE "t_sr"  ADD PRIMARY KEY ("pk_ID");